import type { AutomataCheatTopic } from "./types";

export const unit5Topics: AutomataCheatTopic[] = [
  {
    id: "syntax-analysis-introduction",
    unit: "V",
    title: "Introduction to Syntax Analysis & Role of Parser",
    category: "Syntax Analysis & Grammar Transformations",
    importance: "HIGH",
    definition:
      "Syntax Analysis (Parsing) is the 2nd phase of a compiler. It reads the token stream generated by the Lexical Analyzer, verifies syntactic correctness against a Context-Free Grammar (CFG), and constructs a Parse Tree.",
    coreIdea: "Parser acts as the structural orchestrator: verifying syntax, reporting errors with line numbers, and building syntax tree for semantic analysis.",
    steps: [
      "1. Interface: Calls `getNextToken()` to receive token stream from lexer.",
      "2. Verification: Checks token sequence against CFG production rules.",
      "3. Construction: Builds Parse Tree / Abstract Syntax Tree (AST).",
      "4. Error Handling: Reports syntax errors and performs recovery (panic mode / phrase level).",
    ],
    examPoints: [
      "Draw parser interaction diagram with Lexer, Symbol Table, and Error Handler.",
      "Explain primary tasks of the Parser in compiler pipeline."
    ],
    memoryTrigger: "Parser = Syntactic Inspector. Token Stream In → Parse Tree Out.",
    keywords: ["syntax analysis", "role of parser", "parse tree", "compiler phase 2", "syntax error"],
  },
  {
    id: "topdown-vs-bottomup",
    unit: "V",
    title: "Top-Down Parsing vs Bottom-Up Parsing",
    category: "Syntax Analysis & Grammar Transformations",
    importance: "HIGH",
    definition:
      "Parsing techniques are broadly divided into two strategies: Top-Down Parsing (builds tree from Start Symbol S down to leaves) and Bottom-Up Parsing (builds tree from leaves up to Start Symbol S).",
    coreIdea: "Top-Down uses Leftmost Derivation (LL); Bottom-Up uses Rightmost Derivation in Reverse (LR).",
    differences: [
      { feature: "Top-Down Parsing", valA: "Starts from Start Symbol S down to leaves", valB: "Uses Leftmost Derivation (LL(1), Recursive Descent)" },
      { feature: "Bottom-Up Parsing", valA: "Starts from input leaves up to Start Symbol S", valB: "Uses Reverse Rightmost Derivation (Shift-Reduce, SLR, LALR, CLR)" },
      { feature: "Grammar Restrictions", valA: "Cannot handle Left-Recursive or non-left-factored grammars", valB: "Handles wider class of grammars including left recursion" },
    ],
    examPoints: [
      "Compare Top-Down vs Bottom-Up parsing with respect to derivation order, grammar restrictions, and parser power — 10-mark question.",
      "Explain why Bottom-Up parsing is generally preferred in production compilers (Yacc/Bison)."
    ],
    memoryTrigger: "Top-Down = Root S → Leaves (LL). Bottom-Up = Leaves → Root S (LR).",
    keywords: ["top down parsing", "bottom up parsing", "LL vs LR", "parsing strategies"],
  },
  {
    id: "writing-grammar-left-recursion",
    unit: "V",
    title: "Writing Grammars: Eliminating Left Recursion",
    category: "Syntax Analysis & Grammar Transformations",
    importance: "HIGH",
    definition:
      "A grammar is Left-Recursive if a non-terminal A derives a sentential form starting with A (A ⇒+ Aα). Immediate Left Recursion A → Aα | β causes Top-Down parsers to enter infinite recursion loops. Eliminated by converting to right recursion.",
    coreIdea: "Immediate Left Recursion A → Aα | β is transformed into A → βA' and A' → αA' | ε.",
    steps: [
      "1. Immediate Left Recursion: A → Aα₁ | Aα₂ | ... | β₁ | β₂.",
      "2. Transform to Right Recursion:",
      "   A → β₁A' | β₂A'",
      "   A' → α₁A' | α₂A' | ε",
      "3. Indirect Left Recursion (e.g. A → Bα, B → Aβ): Order variables A₁, A₂... A_n; substitute previous variable rules iteratively.",
    ],
    examPoints: [
      "Eliminate Immediate Left Recursion from arithmetic expression grammar `E → E + T | T` — 10-mark exam classic.",
      "Explain why left-recursive grammars break Top-Down LL(1) predictive parsers."
    ],
    memoryTrigger: "A → Aα | β becomes A → βA', A' → αA' | ε. Eliminates infinite parser loops!",
    keywords: ["left recursion elimination", "immediate left recursion", "indirect left recursion", "right recursion"],
  },
  {
    id: "writing-grammar-left-factoring",
    unit: "V",
    title: "Writing Grammars: Left Factoring Nondeterministic Prefixes",
    category: "Syntax Analysis & Grammar Transformations",
    importance: "HIGH",
    definition:
      "Left Factoring is a grammar transformation that eliminates common prefixes in production RHS alternatives (e.g. A → αβ₁ | αβ₂), resolving nondeterminism for top-down parsers.",
    coreIdea: "Left Factoring deferred the decision of which production to choose until enough input symbols have been seen.",
    steps: [
      "1. Identify common prefix α in productions A → αβ₁ | αβ₂ | ... | γ.",
      "2. Rewrite as A → αA' | γ.",
      "3. Create new rule A' → β₁ | β₂.",
      "4. Example: `S → iEtS | iEtSeS | a` becomes `S → iEtSS' | a` and `S' → eS | ε` (Dangling-Else resolution).",
    ],
    examPoints: [
      "Apply Left Factoring to a given CFG containing common prefixes — guaranteed 5/10-mark question.",
      "Explain how Left Factoring resolves the Dangling-Else ambiguity in programming languages."
    ],
    memoryTrigger: "Left Factoring: A → αβ₁ | αβ₂ becomes A → αA', A' → β₁ | β₂. Resolves prefix choice!",
    keywords: ["left factoring", "common prefixes", "dangling else", "predictive parsing grammar"],
  },
  {
    id: "topdown-recursive-descent",
    unit: "V",
    title: "Top-Down Parsing: Recursive Descent Parsers & Backtracking",
    category: "Top-Down & Bottom-Up Parsing",
    importance: "HIGH",
    definition:
      "Recursive Descent Parsing is a top-down parsing method where a dedicated C/C++ function is written for each non-terminal variable. If a production choice fails, the parser backtracks input and stack states.",
    coreIdea: "Predictive Recursive Descent eliminates backtracking by ensuring 1-symbol lookahead uniquely chooses the correct production function.",
    steps: [
      "1. Write C function `void A()` for non-terminal A.",
      "2. Check current lookahead token against production RHS alternatives.",
      "3. For terminal symbol 'a': match 'a' and advance input; for variable B: call function `B()`.",
      "4. Backtracking: If alternative fails, reset input pointer to start of production attempt.",
    ],
    examPoints: [
      "Write C recursive descent parsing functions for a given simple grammar.",
      "Explain the performance penalty of backtracking in general recursive descent parsers."
    ],
    memoryTrigger: "Recursive Descent = 1 C function per non-terminal variable A().",
    keywords: ["recursive descent", "backtracking parser", "top-down function calls", "lookahead token"],
  },
  {
    id: "topdown-predictive-ll1",
    unit: "V",
    title: "Top-Down Non-Backtracking LL(1) Predictive Parsing",
    category: "Top-Down & Bottom-Up Parsing",
    importance: "HIGH",
    definition:
      "LL(1) is a table-driven non-backtracking top-down parser reading input Left-to-right constructing Leftmost derivation using 1 lookahead symbol. It uses a Stack, an Input Buffer, and an LL(1) Parsing Table M[A, a].",
    coreIdea: "Grammar is LL(1) iff no cell in parsing table M[A, a] contains multiple production entries (no LL(1) conflicts).",
    steps: [
      "1. Calculate FIRST and FOLLOW sets for all non-terminals.",
      "2. For each production A → α: for each terminal a ∈ FIRST(α), add A → α to M[A, a].",
      "3. If ε ∈ FIRST(α): for each terminal b ∈ FOLLOW(A) (including '$'), add A → α to M[A, b].",
      "4. Parse execution: Stack holds grammar symbols; matching top terminal with input pops stack.",
    ],
    examPoints: [
      "Construct LL(1) parsing table for a given grammar.",
      "Trace step-by-step stack execution for input string `id + id * id` on LL(1) parser — guaranteed 10-mark question."
    ],
    memoryTrigger: "LL(1) Parser = Stack + Input Buffer + Table M[A, a]. No multiple entries in M!",
    keywords: ["LL1 parser", "predictive parsing table", "LL1 condition", "stack parsing"],
  },
  {
    id: "first-and-follow-sets",
    unit: "V",
    title: "Calculation Algorithms for FIRST and FOLLOW Sets",
    category: "Top-Down & Bottom-Up Parsing",
    importance: "HIGH",
    definition:
      "FIRST(α) is the set of terminals that can begin strings derived from α. FOLLOW(A) is the set of terminals that can appear immediately to the right of non-terminal A in any sentential form.",
    coreIdea: "FIRST and FOLLOW sets dictate predictive table entries M[A, a] and SLR(1) reduction entries.",
    steps: [
      "1. FIRST(X): If X is terminal, FIRST(X) = {X}. If X → ε, add ε to FIRST(X). If X → Y₁Y₂...Y_k, add FIRST(Y₁) \\ {ε} to FIRST(X).",
      "2. FOLLOW(A): Add '$' to FOLLOW(S) for start symbol S. If A → αBβ, add FIRST(β) \\ {ε} to FOLLOW(B). If A → αB or A → αBβ with ε ∈ FIRST(β), add FOLLOW(A) to FOLLOW(B).",
    ],
    examPoints: [
      "Compute FIRST and FOLLOW sets for all non-terminals in an expression grammar — guaranteed 10-mark question.",
      "Apply FIRST and FOLLOW rules for ε-producing non-terminals."
    ],
    memoryTrigger: "FIRST = terminals starting production RHS. FOLLOW = terminals coming immediately after variable A.",
    keywords: ["FIRST set", "FOLLOW set", "LL1 table construction", "SLR reductions"],
  },
  {
    id: "bottomup-shift-reduce-parsing",
    unit: "V",
    title: "Bottom-Up Parsing: Shift-Reduce Parser Operations & Handle Pruning",
    category: "Top-Down & Bottom-Up Parsing",
    importance: "HIGH",
    definition:
      "Shift-Reduce parsing constructs a parse tree from input leaves up to root S by performing 4 actions: Shift, Reduce, Accept, Error. It traces a Rightmost Derivation in Reverse.",
    coreIdea: "Handle = A substring on top of stack that matches a production RHS A → β and whose reduction represents a step in reverse RMD.",
    steps: [
      "1. Shift: Push next input token onto stack.",
      "2. Reduce: When top of stack matches handle β, replace β with non-terminal A (production A → β).",
      "3. Accept: Stack contains Start Symbol S and input buffer is empty ($).",
      "4. Handle Pruning: Traces right sentential forms backward to find handles for reduction.",
    ],
    examPoints: [
      "Trace step-by-step stack actions (Shift, Reduce) for string `id * id + id`.",
      "Define Handle and Handle Pruning with clear diagrams."
    ],
    memoryTrigger: "Bottom-Up: Shift input → Find Handle β on top of stack → Reduce β to A.",
    keywords: ["Shift-Reduce parsing", "Handle pruning", "bottom-up parsing", "reverse RMD", "stack actions"],
  },
  {
    id: "parsing-conflicts-shift-reduce",
    unit: "V",
    title: "Parser Conflicts: Shift-Reduce & Reduce-Reduce Conflicts",
    category: "Top-Down & Bottom-Up Parsing",
    importance: "HIGH",
    definition:
      "A parsing conflict occurs when a shift-reduce parser table cell contains multiple ambiguous choices. Shift/Reduce conflict: parser cannot decide whether to shift or reduce. Reduce/Reduce conflict: parser cannot decide between 2 productions to reduce.",
    coreIdea: "Conflicts indicate grammar ambiguity or lookahead insufficiency. Resolved by rewriting grammar, setting precedence/associativity rules, or increasing lookahead.",
    differences: [
      { feature: "Shift/Reduce Conflict", valA: "Parser table cell contains both Shift(s_k) and Reduce(r_j) actions", valB: "Often caused by Dangling-Else or missing operator precedence" },
      { feature: "Reduce/Reduce Conflict", valA: "Parser table cell contains multiple Reduce actions (r_i AND r_j)", valB: "Indicates serious grammar ambiguity or overlapping production RHSs" },
    ],
    examPoints: [
      "Identify Shift/Reduce and Reduce/Reduce conflicts in an LR parsing table.",
      "Explain techniques to resolve parsing conflicts using Yacc precedence declarations `%left`, `%right`."
    ],
    memoryTrigger: "Shift/Reduce = Shift vs Reduce choice. Reduce/Reduce = Choice between 2 reductions (Serious error!).",
    keywords: ["shift reduce conflict", "reduce reduce conflict", "parsing conflicts", "grammar ambiguity"],
  },
  {
    id: "lr-parsing-slr1",
    unit: "V",
    title: "LR Parsing: Simple LR (SLR(1)) & LR(0) Canonical Items",
    category: "LR Parsing Family",
    importance: "HIGH",
    definition:
      "SLR(1) is a Simple LR parser that uses LR(0) canonical items `A → α·β` and FOLLOW sets to place reduction entries in the parsing table.",
    coreIdea: "LR(0) Item `A → α·β` represents a parsing state where `α` has been seen on top of stack and `β` is expected next.",
    steps: [
      "1. Construct Augmented Grammar G' by adding S' → S.",
      "2. Compute CLOSURE(I) and GOTO(I, X) sets of LR(0) items.",
      "3. Construct ACTION and GOTO tables: If `[A → α·]` is in state I_i, add Reduce `r_j` to ACTION[i, a] for all a ∈ FOLLOW(A).",
      "4. If conflicts occur in ACTION table, grammar is NOT SLR(1).",
    ],
    examPoints: [
      "Construct LR(0) canonical collection of items for a given grammar.",
      "Build SLR(1) parsing table and check for SLR(1) conflicts — 10-mark guaranteed numerical."
    ],
    memoryTrigger: "SLR(1) = LR(0) items + FOLLOW sets for reductions. Simple & compact.",
    keywords: ["SLR1", "LR0 items", "CLOSURE", "GOTO", "SLR parsing table"],
  },
  {
    id: "lr-parsing-lalr1",
    unit: "V",
    title: "LR Parsing: Lookahead LR (LALR(1)) Parsing",
    category: "LR Parsing Family",
    importance: "HIGH",
    definition:
      "LALR(1) (Lookahead LR) merges CLR(1) states that have identical LR(0) cores (same dotted productions), drastically reducing state count while maintaining lookahead precision.",
    coreIdea: "LALR(1) has the same number of states as SLR(1), but eliminates almost all false Shift/Reduce conflicts found in SLR(1). Default engine for Yacc & Bison.",
    differences: [
      { feature: "SLR(1) vs LALR(1)", valA: "SLR uses FOLLOW(A) for reductions", valB: "LALR uses precise LR(1) lookaheads; far more powerful" },
      { feature: "CLR(1) vs LALR(1)", valA: "CLR maintains full distinct LR(1) states (hundreds of states)", valB: "LALR merges states with same core (same state count as SLR)" },
    ],
    examPoints: [
      "Explain state merging algorithm in LALR(1) parsing table construction.",
      "Demonstrate why merging CLR states cannot create new Shift/Reduce conflicts (can only introduce Reduce/Reduce conflicts)."
    ],
    memoryTrigger: "LALR(1) = Merges CLR states with same core. Practical power of CLR + compact size of SLR!",
    keywords: ["LALR1", "Yacc Bison default", "merged LR1 cores", "compact lookahead parsing"],
  },
  {
    id: "lr-parsing-clr1",
    unit: "V",
    title: "LR Parsing: Canonical LR (CLR(1)) Parsing",
    category: "LR Parsing Family",
    importance: "HIGH",
    definition:
      "Canonical LR (CLR(1)) parsing uses full LR(1) items `[A → α·β, a]` where `a` is an explicit 1-symbol lookahead terminal specifying exact valid reduction contexts.",
    coreIdea: "CLR(1) is the most powerful deterministic bottom-up parsing algorithm, recognizing all LR(1) grammars.",
    formula: {
      expression: "LR(1) Item: [A → α·β, a]   •   a ∈ T ∪ {$}",
      symbols: { "A → α·β": "Production & dot position", a: "Lookahead terminal specifying reduction context" },
    },
    steps: [
      "1. Construct LR(1) item CLOSURE([A → α·Bβ, a]): for each production B → γ, add [B → ·γ, b] for all b ∈ FIRST(βa).",
      "2. Compute GOTO(I, X) for LR(1) item sets.",
      "3. Reduce entries are placed ONLY in column `a` for item `[A → α·, a]` (not full FOLLOW set!).",
    ],
    examPoints: [
      "Construct CLR(1) canonical collection of items for a small grammar.",
      "Compare parser hierarchy: SLR(1) ⊂ LALR(1) ⊂ CLR(1)."
    ],
    memoryTrigger: "CLR(1) = Full LR(1) items [A → α·β, a]. Most powerful, but large state count.",
    keywords: ["CLR1", "Canonical LR", "LR1 items", "lookahead item", "parser hierarchy"],
  },
  {
    id: "sdd-syntax-directed-definitions",
    unit: "V",
    title: "Syntax-Directed Definitions (SDD): Synthesized vs Inherited",
    category: "Syntax-Directed Translation (SDT)",
    importance: "HIGH",
    definition:
      "A Syntax-Directed Definition (SDD) associates attributes with grammar symbols and semantic rules with productions. Attributes are evaluated during parse tree traversal.",
    coreIdea: "Synthesized attributes flow bottom-up (children → parent). Inherited attributes flow top-down or sideways (parent/left-siblings → node).",
    differences: [
      { feature: "Synthesized Attribute", valA: "Node value computed from children attributes: A.s = f(X.s, Y.s)", valB: "Evaluated bottom-up post reduction" },
      { feature: "Inherited Attribute", valA: "Node value computed from parent or left-sibling attributes: Y.i = f(A.i, X.s)", valB: "Evaluated top-down or left-to-right" },
      { feature: "S-Attributed SDD", valA: "Uses ONLY Synthesized Attributes", valB: "Implemented naturally during Bottom-Up LR parsing" },
      { feature: "L-Attributed SDD", valA: "Synthesized + Inherited (dependencies restricted to parent & left siblings)", valB: "Implemented during Left-to-Right depth-first traversals" },
    ],
    examPoints: [
      "Differentiate Synthesized vs Inherited attributes and S-Attributed vs L-Attributed SDDs with clear examples — guaranteed 10-mark question.",
      "Construct annotated parse tree for an arithmetic expression using an SDD."
    ],
    memoryTrigger: "Synthesized = Arrow UP (from children). Inherited = Arrow DOWN/LEFT (from parent/left-siblings).",
    keywords: ["SDD", "syntax directed definition", "synthesized attributes", "inherited attributes", "S-attributed", "L-attributed"],
  },
  {
    id: "sdd-evaluation-orders-dependency",
    unit: "V",
    title: "Evaluation Orders for SDDs & Dependency Graphs",
    category: "Syntax-Directed Translation (SDT)",
    importance: "HIGH",
    definition:
      "Evaluation Order for an SDD determines the sequence in which attribute values are computed. Constructed by creating a Dependency Graph for parse tree nodes and finding a Topological Sort.",
    coreIdea: "A valid evaluation order exists if and only if the dependency graph has no directed cycles.",
    steps: [
      "1. Construct Parse Tree for input string.",
      "2. For each attribute instance at a parse tree node, add a graph node.",
      "3. Add directed edge N₁ → N₂ if attribute N₂ depends on value of attribute N₁.",
      "4. Apply Topological Sort: any topological order of DAG nodes is a valid attribute evaluation sequence.",
    ],
    examPoints: [
      "Construct Dependency Graph for an annotated parse tree and determine valid topological evaluation order — 10-mark question.",
      "Explain why directed cycles in dependency graph render SDD non-evaluable."
    ],
    memoryTrigger: "Dependency Graph: Edges from source attribute to dependent attribute. Topological sort = valid evaluation sequence.",
    keywords: ["evaluation order", "dependency graph", "topological sort", "annotated parse tree", "attribute dependency"],
  },
  {
    id: "sdts-translation-schemes",
    unit: "V",
    title: "Syntax-Directed Translation Schemes (SDTS) & L-Attributed Implementation",
    category: "Syntax-Directed Translation (SDT)",
    importance: "HIGH",
    definition:
      "A Syntax-Directed Translation Scheme (SDTS) embeds semantic actions `{ action_code }` directly into production right-hand sides. L-Attributed SDDs are implemented during Top-Down LL or Bottom-Up LR parsing.",
    coreIdea: "Postfix SDTS places all semantic actions at the end of production RHS, making it ideal for bottom-up LR parser reduction actions.",
    steps: [
      "1. Postfix SDTS: Actions placed at RHS end (e.g., E → E₁ + T { E.val = E₁.val + T.val }). Executed upon reduction.",
      "2. L-Attributed SDD in Top-Down Parsing: Inherited attributes computed before parsing child non-terminal.",
      "3. L-Attributed SDD in Bottom-Up Parsing: Insert marker non-terminals M → ε to execute embedded actions on stack.",
    ],
    examPoints: [
      "Convert an L-Attributed SDD into an SDTS with embedded actions.",
      "Explain how Postfix SDTS is implemented on an LR parser stack."
    ],
    memoryTrigger: "SDTS = CFG + embedded `{ actions }`. Postfix SDTS = Actions at RHS end (perfect for LR reduction).",
    keywords: ["SDTS", "translation scheme", "embedded actions", "postfix SDTS", "L-attributed implementation"],
  },
  {
    id: "intermediate-code-ast-dag-tac",
    unit: "V",
    title: "Intermediate Code Generation: AST, DAG, Three-Address Code (TAC), Quadruples & Triples",
    category: "Intermediate Code Generation (ICG)",
    importance: "HIGH",
    definition:
      "Intermediate Code Generation produces an abstract machine-independent representation. Abstract Syntax Trees (AST) condense parse trees; Directed Acyclic Graphs (DAG) detect common subexpressions; Three-Address Code (TAC) represents linear instructions (`x = y op z`).",
    coreIdea: "TAC decouples language syntax from target machine details. Stored using Quadruples `(op, arg1, arg2, res)`, Triples `(op, arg1, arg2)`, or Indirect Triples.",
    formula: {
      expression: "x = y OP z   •   x = OP y   •   if x relop y goto L   •   param x   •   call p, n",
      symbols: { x: "Destination variable", y: "Operand 1", z: "Operand 2", OP: "Operator" },
    },
    differences: [
      { feature: "Quadruples", valA: "4 Fields: `(op, arg1, arg2, result)`", valB: "Explicit temporary names; easy code reordering during optimization" },
      { feature: "Triples", valA: "3 Fields: `(op, arg1, arg2)`", valB: "Implicit result via index `(i)`; avoids temporary names, hard to reorder" },
      { feature: "Indirect Triples", valA: "Array of pointers to triples list", valB: "Easy reordering by modifying pointer array without moving triples" },
    ],
    examPoints: [
      "Construct AST and DAG for expression `a + a * (b - c) + (b - c) * d` — guaranteed 10-mark question.",
      "Convert arithmetic statement `a = b * -c + b * -c` into TAC, Quadruples, and Triples tables."
    ],
    memoryTrigger: "AST (Condensed) → DAG (Shared common subexpressions) → TAC (Max 3 addresses per line).",
    keywords: ["AST", "DAG", "Three-Address Code", "TAC", "Quadruples", "Triples", "Indirect Triples", "Intermediate Code"],
  },
];


