import type { AutomataCheatTopic } from "./types";

export const unit2Topics: AutomataCheatTopic[] = [
  {
    id: "re-definition-syntax",
    unit: "II",
    title: "Regular Expressions: Formal Definition & Syntax Rules",
    category: "Regular Expressions & Laws",
    importance: "HIGH",
    definition:
      "A Regular Expression (RE) over alphabet Σ is defined inductively: Base cases are ∅ (empty language), ε (empty string), and symbol a ∈ Σ. Recursive steps build expressions using Union (R+S), Concatenation (RS), and Kleene Star (R*).",
    coreIdea: "REs are declarative pattern definitions describing the exact same class of languages as Finite Automata (Regular Languages).",
    formula: {
      expression: "Base: ∅, ε, a   •   Recursive: (R+S), (RS), (R*)",
      symbols: { "∅": "Empty language (no strings)", ε: "Empty string (language {ε})", a: "Single symbol language {a}", "+": "Union / Choice", "*": "Kleene Star" },
    },
    examPoints: [
      "State the inductive 6-clause formal definition of Regular Expressions.",
      "Evaluate language L(R) generated by a given Regular Expression R."
    ],
    memoryTrigger: "RE Base Cases: ∅, ε, a. Operations: Union (+), Concat (·), Star (*).",
    keywords: ["regular expression definition", "RE syntax", "base cases", "Kleene star"],
  },
  {
    id: "re-fa-relationship",
    unit: "II",
    title: "Relationship Between Finite Automata and Regular Expressions",
    category: "Regular Expressions & Laws",
    importance: "HIGH",
    definition:
      "Kleene's Theorem proves that a language L is regular if and only if L can be specified by a Regular Expression R, accepted by a DFA M_DFA, accepted by an NFA M_NFA, or accepted by an ε-NFA M_ε.",
    coreIdea: "Finite Automata and Regular Expressions are completely equivalent in expressive power.",
    differences: [
      { feature: "Regular Expressions (RE)", valA: "Declarative: describes WHAT strings look like", valB: "Used in lexical specifications & pattern matching" },
      { feature: "Finite Automata (FA)", valA: "Operational: describes HOW to check string step-by-step", valB: "Used in lexer engines & hardware controllers" },
    ],
    examPoints: [
      "State Kleene's Equivalence Theorem.",
      "Explain Thompson's Construction algorithm for building an ε-NFA from a Regular Expression."
    ],
    memoryTrigger: "Kleene's Theorem: RE ≡ ε-NFA ≡ NFA ≡ DFA (All describe Regular Languages).",
    keywords: ["Kleene theorem", "RE FA equivalence", "Thompson construction", "expressive power"],
  },
  {
    id: "re-applications",
    unit: "II",
    title: "Applications of Regular Expressions in Computing",
    category: "Regular Expressions & Laws",
    importance: "HIGH",
    definition:
      "Regular Expressions are applied extensively across computer science: lexical analysis in compilers (Flex), command-line text processing tools (grep, sed, awk), and input validation (email/URL validation).",
    coreIdea: "Compiler lexers use REs to define token patterns (identifiers, floating-point literals, keywords).",
    steps: [
      "1. Compiler Lexer Tokens: Identifier pattern `[a-zA-Z_][a-zA-Z0-9_]*`.",
      "2. Integer Literal pattern `[0-9]+`.",
      "3. Floating Point pattern `[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?`.",
    ],
    examPoints: [
      "Write Regular Expressions for identifier and numeric literal token specifications.",
      "Explain the role of REs in text processing tools and lexical scanners."
    ],
    memoryTrigger: "RE Applications: Lexer tokens, grep search, input validation formulas.",
    keywords: ["RE applications", "lexer pattern", "grep", "input validation", "token rules"],
  },
  {
    id: "re-algebraic-laws",
    unit: "II",
    title: "Algebraic Laws for Regular Expressions",
    category: "Regular Expressions & Laws",
    importance: "HIGH",
    definition:
      "Regular Expressions satisfy algebraic identities for Union (+), Concatenation (·), and Kleene Star (*), enabling algebraic simplification of expression formulas.",
    coreIdea: "Key Laws: Commutative (R+S = S+R), Associative ((R+S)+T = R+(S+T)), Idempotent (R+R = R), Distributive (L(M+N) = LM + LN), and Star Laws.",
    formula: {
      expression: "(R*)* = R*   •   ε + RR* = R*   •   (R + S)* = (R* S*)*",
      symbols: { "R+R=R": "Idempotent Union", "(R*)*=R*": "Star Iteration", "L(M+N)=LM+LN": "Distributivity" },
    },
    examPoints: [
      "State and prove algebraic laws for Regular Expressions.",
      "Simplify complex Regular Expressions using algebraic identities."
    ],
    memoryTrigger: "(R*)* = R*. Union is commutative & idempotent. Concat is NOT commutative!",
    keywords: ["algebraic laws", "RE identities", "idempotent law", "distributive law", "star laws"],
  },
  {
    id: "fa-to-re-ardens",
    unit: "II",
    title: "Conversion of FA to Regular Expressions via Arden's Theorem",
    category: "FA to RE Conversions",
    importance: "HIGH",
    definition:
      "Arden's Theorem solves linear state equations of a Finite Automaton to find an equivalent Regular Expression. If P does not contain ε, then state equation R = Q + RP has the unique solution R = QP*.",
    coreIdea: "Set up linear equation for each state q_i = ∑ q_j · label(q_j → q_i) (+ ε for q₀). Solve for final state using R = Q + RP ⟹ R = QP*.",
    formula: {
      expression: "R = Q + RP   ⟹   R = Q P*   (Condition: ε ∉ P)",
      symbols: { R: "Target state expression", Q: "Base incoming terms", P: "Self-loop transition factor" },
      examNote: "If P contains ε, R = QP* is a valid solution but NOT unique!",
    },
    steps: [
      "1. Write state equation for every state in FA: q_i = ∑ q_j · label(q_j → q_i) (+ ε for start state q₀).",
      "2. Substitute equations into each other to isolate final state expressions.",
      "3. Apply Arden's Theorem (R = Q + RP ⟹ R = QP*) whenever a state references itself in a loop.",
      "4. Combine expressions for all final states: R_total = ∑_{q_f ∈ F} q_f.",
    ],
    examPoints: [
      "State Arden's Theorem formally with uniqueness condition (ε ∉ P).",
      "Convert a given 3-state or 4-state DFA to equivalent Regular Expression — guaranteed 10-mark question."
    ],
    memoryTrigger: "R = Q + RP ⟹ R = QP*. Eliminates recursive self-loops in state equations.",
    keywords: ["Ardens Theorem", "FA to RE", "state equations", "regular expression conversion"],
  },
  {
    id: "fa-to-re-state-elimination",
    unit: "II",
    title: "Conversion of FA to RE via State Elimination Algorithm",
    category: "FA to RE Conversions",
    importance: "HIGH",
    definition:
      "The State Elimination Algorithm converts a Finite Automaton to a Regular Expression by iteratively removing non-start/non-final interior states and replacing transition paths with equivalent regular expressions on edges.",
    coreIdea: "When eliminating state q_k with incoming path R_1 to q_k, self-loop R_2 on q_k, and outgoing path R_3 to q_m: replace with direct edge R_1 (R_2)* R_3.",
    steps: [
      "1. Add new start state q_{start} with ε-transition to q₀; add new single final state q_{final} with ε-transitions from all original final states in F.",
      "2. Pick an intermediate state q_k to eliminate (other than q_{start} and q_{final}).",
      "3. For every pair of states q_i and q_j (where q_i → q_k → q_j): new label R_{ij}' = R_{ij} + R_{ik} (R_{kk})* R_{kj}.",
      "4. Repeat state elimination until only q_{start} and q_{final} remain. The edge label q_{start} → q_{final} is the result RE.",
    ],
    examPoints: [
      "Convert a DFA to RE using the State Elimination Algorithm step-by-step.",
      "Compare State Elimination vs Arden's Theorem methods."
    ],
    memoryTrigger: "State Elimination: Replace path i → k → j with R_{ik} (R_{kk})* R_{kj}.",
    keywords: ["state elimination", "FA to RE", "bypassing states", "regular expression conversion"],
  },
  {
    id: "pumping-lemma-statement",
    unit: "II",
    title: "Statement of Pumping Lemma for Regular Languages",
    category: "Pumping Lemma for Regular Languages",
    importance: "HIGH",
    definition:
      "The Pumping Lemma states that if L is a regular language, there exists an integer p ≥ 1 (pumping length) such that every string w ∈ L with |w| ≥ p can be split into w = xyz satisfying 3 conditions: |xy| ≤ p, |y| ≥ 1, and x y^i z ∈ L for all i ≥ 0.",
    coreIdea: "Pumping Lemma is a necessary property of ALL regular languages stemming from the Pigeonhole Principle on finite states.",
    formula: {
      expression: "∀ w ∈ L (|w| ≥ p)  ∃ w = xyz :   (1) |xy| ≤ p   (2) |y| ≥ 1   (3) ∀ i ≥ 0 (x y^i z ∈ L)",
      symbols: { p: "Pumping length", "x,y,z": "Decomposition components", y: "Pumpable substring (|y| ≥ 1)" },
    },
    examPoints: [
      "State the formal theorem of Pumping Lemma for Regular Languages including all 3 conditions.",
      "Explain how the Pigeonhole Principle creates a state loop when string length |w| exceeds state count |Q|."
    ],
    memoryTrigger: "Pumping Lemma 3 Rules: (1) |xy| ≤ p, (2) |y| ≥ 1, (3) x y^i z ∈ L for all i ≥ 0.",
    keywords: ["Pumping Lemma statement", "pumping length", "Pigeonhole Principle", "regular language property"],
  },
  {
    id: "pumping-lemma-applications",
    unit: "II",
    title: "Applications of Pumping Lemma: Non-Regularity Proofs",
    category: "Pumping Lemma for Regular Languages",
    importance: "HIGH",
    definition:
      "The Pumping Lemma is used as a proof technique by contradiction to prove that a language is NOT regular. If pumping y outside the language produces a string ∉ L, then L cannot be regular.",
    coreIdea: "To prove L non-regular: assume L regular with pumping length p; pick string w ∈ L (|w| ≥ p); analyze all decompositions w = xyz; show x y^i z ∉ L for some i.",
    steps: [
      "1. Assume L is regular with pumping length p.",
      "2. Select a target string w ∈ L with |w| ≥ p (e.g. w = a^p b^p).",
      "3. Analyze decomposition w = xyz with |xy| ≤ p and |y| ≥ 1 (forces y = a^k with k ≥ 1).",
      "4. Pump y: choose i = 2 ⟹ x y² z = a^{p+k} b^p. Since p+k ≠ p, x y² z ∉ L (Contradiction!).",
      "5. Conclude by contradiction that L is NOT regular.",
    ],
    examPoints: [
      "Prove L = {aⁿbⁿ | n ≥ 0} is NOT regular using Pumping Lemma — guaranteed 10-mark question.",
      "Prove L = {w w^R | w ∈ {a,b}*} or L = {a^{n²} | n ≥ 1} is NOT regular."
    ],
    memoryTrigger: "w = xyz ⟹ pump y^i (e.g. i=2 or i=0) ⟹ string leaves L ⟹ L is NOT regular!",
    keywords: ["pumping lemma applications", "proof by contradiction", "non-regular proof", "a^n b^n proof"],
  },
  {
    id: "cfg-formal-definition",
    unit: "II",
    title: "Context-Free Grammars (CFG) Formal 4-Tuple Definition",
    category: "Context-Free Grammars (CFG)",
    importance: "HIGH",
    definition:
      "A Context-Free Grammar (CFG) is a 4-tuple G = (V, T, P, S) where V is a finite set of Variables (Non-terminals), T is a finite set of Terminals (alphabet symbols), P is a finite set of Production Rules of form A → α (with A ∈ V, α ∈ (V ∪ T)*), and S ∈ V is the Start Symbol.",
    coreIdea: "CFGs are 'context-free' because production variable A on LHS can be replaced by α regardless of surrounding context.",
    formula: {
      expression: "G = (V, T, P, S)   •   Production A → α (A ∈ V, α ∈ (V ∪ T)*)",
      symbols: { V: "Variables (Non-terminals)", T: "Terminals", P: "Production rules", S: "Start symbol" },
    },
    examPoints: [
      "State formal 4-tuple definition of Context-Free Grammar.",
      "Distinguish Variables V (upper case) vs Terminals T (lower case symbols)."
    ],
    memoryTrigger: "CFG 4-Tuple: G = (V, T, P, S). A → α (Single Variable on LHS).",
    keywords: ["CFG formal definition", "4-tuple", "variables", "terminals", "production rules"],
  },
  {
    id: "cfg-derivations-lmd-rmd",
    unit: "II",
    title: "Derivations Using a Grammar: Leftmost (LMD) vs Rightmost (RMD)",
    category: "Context-Free Grammars (CFG)",
    importance: "HIGH",
    definition:
      "A Derivation replaces non-terminals with production right-hand sides step-by-step. Leftmost Derivation (LMD) replaces the leftmost variable at every step; Rightmost Derivation (RMD) replaces the rightmost variable at every step.",
    coreIdea: "LMD is used by Top-Down parsers (LL); Rightmost Derivation in Reverse is used by Bottom-Up parsers (LR).",
    differences: [
      { feature: "Leftmost Derivation (LMD)", valA: "Always replaces leftmost non-terminal variable first", valB: "Generates sentence left-to-right (used by LL parsers)" },
      { feature: "Rightmost Derivation (RMD)", valA: "Always replaces rightmost non-terminal variable first", valB: "Reverse RMD traces bottom-up reductions (used by LR parsers)" },
    ],
    examPoints: [
      "Construct Leftmost and Rightmost Derivations for a given string w in a CFG.",
      "Show that LMD and RMD produce identical parse tree yields."
    ],
    memoryTrigger: "LMD = Expand left variable first. RMD = Expand right variable first.",
    keywords: ["LMD", "RMD", "leftmost derivation", "rightmost derivation", "derivation step"],
  },
  {
    id: "cfg-language-construction",
    unit: "II",
    title: "The Language of a Grammar L(G) & Grammar Design",
    category: "Context-Free Grammars (CFG)",
    importance: "HIGH",
    definition:
      "The Language of a Grammar L(G) is the set of all terminal strings w ∈ T* that can be derived from start symbol S in one or more steps (S ⇒* w).",
    coreIdea: "CFGs model matching patterns and recursion beyond Regular Languages (e.g. balanced parentheses, palindromes).",
    steps: [
      "1. L = {aⁿbⁿ | n ≥ 1}: Production S → aSb | ab.",
      "2. Balanced Parentheses: Production S → (S)S | ε.",
      "3. Palindromes over {a,b}: Production S → aSa | bSb | a | b | ε.",
    ],
    examPoints: [
      "Define L(G) formally using multi-step derivation relation ⇒*.",
      "Design CFGs for given formal languages — guaranteed exam numerical."
    ],
    memoryTrigger: "L(G) = { w ∈ T* | S ⇒* w }. CFGs design recursive matching languages.",
    keywords: ["language of grammar", "L(G)", "CFG design", "balanced parentheses", "palindromes"],
  },
  {
    id: "cfg-parse-trees",
    unit: "II",
    title: "Parse Trees: Graphical Representation of Derivations",
    category: "Context-Free Grammars (CFG)",
    importance: "HIGH",
    definition:
      "A Parse Tree is a graphical tree representation of a derivation. Root is Start Symbol S; Interior nodes are Variables V; Leaves are Terminals T (or ε). Reading leaf labels left-to-right yields string w.",
    coreIdea: "Parse Tree abstracts away derivation order: 1 Parse Tree corresponds to exactly 1 Leftmost Derivation and 1 Rightmost Derivation.",
    steps: [
      "1. Root node labeled with Start Symbol S.",
      "2. For production A → X₁X₂...X_k, create child nodes X₁, X₂... X_k under parent node A.",
      "3. Leaf nodes are labeled with terminals T or ε.",
      "4. Concatenation of leaves from left to right forms the Yield of the parse tree.",
    ],
    examPoints: [
      "Construct Parse Tree for a target string in a given CFG.",
      "Demonstrate the equivalence between Parse Tree yield and string w."
    ],
    memoryTrigger: "Parse Tree: Root S, Internal Variables V, Leaves Terminals T. Yield = Left-to-Right leaves.",
    keywords: ["parse tree", "yield", "derivation tree", "tree leaves", "hierarchical structure"],
  },
  {
    id: "cfg-ambiguity-proofs",
    unit: "II",
    title: "Ambiguity in Grammars & Languages",
    category: "Context-Free Grammars (CFG)",
    importance: "HIGH",
    definition:
      "A Context-Free Grammar is ambiguous if there exists at least one string w ∈ L(G) that has 2 or more distinct parse trees (or 2+ distinct Leftmost Derivations).",
    coreIdea: "Ambiguity is dangerous in compilers because different parse trees yield conflicting evaluation trees for the same expression.",
    steps: [
      "1. Consider ambiguous expression grammar E → E + E | E * E | (E) | id.",
      "2. Select string w = `id + id * id`.",
      "3. Tree 1: Groups `(id + id) * id` (evaluates '+' first).",
      "4. Tree 2: Groups `id + (id * id)` (evaluates '*' first).",
      "5. Multiple parse trees for string w prove grammar G is ambiguous.",
    ],
    examPoints: [
      "Prove a given grammar is ambiguous by constructing 2 distinct parse trees for 1 string — guaranteed 10-mark question.",
      "Differentiate Ambiguous Grammar vs Inherently Ambiguous Language."
    ],
    memoryTrigger: "Ambiguous Grammar = 2+ parse trees for 1 single string!",
    keywords: ["ambiguity", "ambiguous grammar", "multiple parse trees", "inherently ambiguous"],
  },
  {
    id: "cfg-disambiguation-precedence",
    unit: "II",
    title: "Disambiguation Techniques: Operator Precedence & Associativity",
    category: "Context-Free Grammars (CFG)",
    importance: "HIGH",
    definition:
      "Disambiguation rewrites an ambiguous expression grammar into an equivalent unambiguous grammar by stratifying non-terminals into explicit operator precedence and associativity levels.",
    coreIdea: "Structure non-terminals: Expression (E) handles addition/subtraction; Term (T) handles multiplication/division; Factor (F) handles atomic operands and parentheses.",
    steps: [
      "1. Ambiguous: E → E + E | E * E | (E) | id.",
      "2. Unambiguous (Precedence: * over +, Left-associative):",
      "   E → E + T | T   (Lowest precedence: +)",
      "   T → T * F | F   (Higher precedence: *)",
      "   F → (E) | id    (Highest precedence: atomic)",
    ],
    examPoints: [
      "Rewrite ambiguous arithmetic grammar into unambiguous grammar introducing Term (T) and Factor (F) — guaranteed 10-mark question.",
      "Explain how left recursion in E → E + T forces left-associativity."
    ],
    memoryTrigger: "Disambiguation: E (expr) → T (term) → F (factor). Enforces operator precedence & associativity.",
    keywords: ["disambiguation", "operator precedence", "associativity", "Term Factor grammar", "unambiguous grammar"],
  },
];


