-- Widen action column and add known action constraint
ALTER TABLE public.audit_logs
  ALTER COLUMN action TYPE VARCHAR(100);

ALTER TABLE public.audit_logs
  ADD CONSTRAINT audit_logs_action_known
  CHECK (action IN (
    'LOGIN', 'LOGOUT', 'LOGIN_FAILED',
    'PASS_CREATED', 'PASS_APPROVED', 'PASS_REJECTED', 'GATE_PASS_CREATED',
    'GATE_PASS_APPROVED', 'GATE_PASS_REJECTED', 'GATE_PASS_UPDATED',
    'SCAN_CREATED', 'GATE_SCAN_RECORDED', 'SCAN_CORRECTED',
    'VISITOR_CHECK_IN', 'VISITOR_CHECK_OUT',
    'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_DEACTIVATED',
    'ROLE_CHANGED', 'PERMISSION_CHANGED',
    'SYSTEM_CONFIG_CHANGED', 'DATA_EXPORTED',
    'BACKUP_CREATED', 'BACKUP_RESTORED',
    'EMERGENCY_BROADCAST', 'GATE_OFFLINE', 'GATE_ONLINE',
    'SMART_SCHEDULE_APPLIED', 'CRON_REPORTS_EXECUTED',
    'PIN_CHANGED', 'SESSION_FORCE_REVOKED', 'SESSION_VERSION_BUMP',
    'BACK_GATE_GEO_MISMATCH', 'REFRESH_REVOKED_TOKEN_USED',
    'THUMBPRINT_REGISTERED', 'THUMBPRINT_CLEARED',
    'MFA_ENROLL_REPLAY_BLOCKED', 'EMERGENCY_MFA_TOKEN_GENERATED',
    'MFA_RECOVERY_CODES_REGENERATED', 'MFA_OVERRIDE_ACTIVE',
    'FILE_UPLOADED', 'BULK_STUDENT_UPDATE', 'BATCH_PROMOTION',
    'ALERT_RESOLVE_DENIED', 'ALERT_RESOLVED',
    'HOD_CROSS_DEPT_ATTEMPT', 'SUPPORT_TICKET_UPDATED',
    'RETENTION_RUN', 'PREDICTIONS_RETRAINED',
    'GATE_PASS_BULK_APPROVED', 'ADMIN_STREAM_OTHER_USER',
    'MFA_REQUIRED_FOR_ADMIN_CHANGED', 'ROLE_REGISTRY_CHANGED'
  ));
