-- 20261014000000_enrollment_codes_and_user_roles.sql
BEGIN;

-- 1. Enrollment Codes
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='mobile_enrollment_codes') THEN
    ALTER TABLE public.mobile_enrollment_codes RENAME TO enrollment_codes;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.enrollment_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.enrollment_codes ADD COLUMN IF NOT EXISTS purpose TEXT NOT NULL DEFAULT 'mobile' CHECK (purpose IN ('mobile', 'web'));

-- 2. User Roles
CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, role)
);

INSERT INTO public.user_roles (user_id, role)
SELECT id, role FROM users ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION sync_primary_role() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO user_roles (user_id, role) VALUES (NEW.id, NEW.role)
  ON CONFLICT (user_id, role) DO NOTHING;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_primary_role ON public.users;
CREATE TRIGGER trg_sync_primary_role AFTER INSERT OR UPDATE OF role ON public.users
  FOR EACH ROW EXECUTE FUNCTION sync_primary_role();

-- 3. Audit Logs
ALTER TABLE public.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_action_known;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_action_known
  CHECK (action IN (
    'LOGIN','LOGOUT','LOGIN_FAILED',
    'PASS_CREATED','PASS_APPROVED','PASS_REJECTED','GATE_PASS_CREATED',
    'GATE_PASS_APPROVED','GATE_PASS_REJECTED','GATE_PASS_UPDATED',
    'SCAN_CREATED','GATE_SCAN_RECORDED','SCAN_CORRECTED','MOVEMENT_CREATED',
    'VISITOR_CHECK_IN','VISITOR_CHECK_OUT',
    'USER_CREATED','USER_UPDATED','USER_DELETED','USER_DEACTIVATED',
    'ROLE_CHANGED','ACCOUNT_STATUS_CHANGED','PERMISSION_CHANGED',
    'SYSTEM_CONFIG_CHANGED','DATA_EXPORTED',
    'BACKUP_CREATED','BACKUP_RESTORED',
    'EMERGENCY_BROADCAST','GATE_OFFLINE','GATE_ONLINE',
    'SMART_SCHEDULE_APPLIED','CRON_REPORTS_EXECUTED',
    'PIN_CHANGED','PASSWORD_CHANGED',
    'SESSION_FORCE_REVOKED','SESSION_VERSION_BUMP',
    'BACK_GATE_GEO_MISMATCH','REFRESH_REVOKED_TOKEN_USED',
    'THUMBPRINT_REGISTERED','THUMBPRINT_CLEARED',
    'MFA_ENROLL_REPLAY_BLOCKED','EMERGENCY_MFA_TOKEN_GENERATED',
    'MFA_RECOVERY_CODES_REGENERATED','MFA_OVERRIDE_ACTIVE',
    'FILE_UPLOADED','BULK_STUDENT_UPDATE','BATCH_PROMOTION',
    'ALERT_RESOLVE_DENIED','ALERT_RESOLVED',
    'HOD_CROSS_DEPT_ATTEMPT','SUPPORT_TICKET_UPDATED',
    'RETENTION_RUN','PREDICTIONS_RETRAINED',
    'GATE_PASS_BULK_APPROVED','ADMIN_STREAM_OTHER_USER',
    'MFA_REQUIRED_FOR_ADMIN_CHANGED','ROLE_REGISTRY_CHANGED',
    'PHOTO_CAPTURED','PHOTO_CAPTURE_CONSENT_DENIED',
    'MANUAL_ENTRY_AUTHORIZED','MANUAL_ENTRY_DENIED',
    'MOVEMENT_CREATED', 'ACCOUNT_STATUS_CHANGED', 'ENROLLMENT_CODE_ISSUED', 'ENROLLMENT_CODE_REDEEMED', 'ENROLLMENT_CODE_REJECTED', 'USER_ONBOARDED', 'ROLE_GRANTED', 'ROLE_REVOKED', 'MOBILE_ENROLLMENT_CODE_ISSUED'
  ));

COMMIT;
